# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: true
    view:
        view_response_listener:  'force'
    body_converter:
        enabled: true
    param_fetcher_listener: true
    format_listener:
            rules:
                - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }



sensio_framework_extra:
    view:
        annotations: true
    request:
        converters: true
        auto_convert: true
    router:
        annotations: true
    cache:
        annotations: true
    security:
        annotations: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
